datamodule:
  _target_: utils.calvin_utils.HulcDataModule
  _recursive_: false

  root_data_dir: ${root_data_dir}  
  action_space: 7
  action_max: [1., 1., 1., 1., 1., 1., 1.,]
  action_min: [-1., -1., -1., -1., -1., -1., -1]
  shuffle_val: false

  observation_space:
    rgb_obs: ['rgb_static', 'rgb_gripper']
    depth_obs: []
    state_obs: [] #['robot_obs', 'scene_obs']
    actions: ['rel_actions']
    language: ['language']

  proprioception_dims:
    n_state_obs: 8
    keep_indices: [[0, 7], [14,15]]
    robot_orientation_idx: [3, 6]
    normalize: True
    normalize_robot_orientation: True


model_family: 'openvla'
ep_len: 200
num_sequences: 50
num_videos: 0
lang_embeddings: null
render: false
log_wandb: true
debug: false
wandb:
  entity: grig-guz
device: 0
cfg_value: 1
use_egl: true
seed: 999